### ISSUE TITLE
The “app” hotlinks images from the wiki

### ISSUE THREAD

**Issue by Yuubari** [HotFireyDeath/azurviewer#10]
As described.

Are you sure you thought this through well? Would you love it if someone wrote an “app” that does 600 requests to your server per second and essentially takes your bandwidth for free?

Why are you not hosting the images yourself?

-- Yuubari, Azur Lane Wiki hostmaster

**Comment by HotFireyDeath** [comment]
Apologies,
I will address this as soon as possible. I didn't think many people would use the app to cause notable bandwidth usage, but thank you for notifying me quickly.

**Comment by Yuubari** [comment]
It is not exactly a problem with bandwidth, but rather the approach. I would probably not have noticed this if it followed browser connection queue defaults. It took all of the available PHP processes when normally there are 95+ spares, resulting in regular users getting service unavailable errors.
